/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as baseAuctionSol from "./BaseAuction.sol";
export { AuctionFactory__factory } from "./AuctionFactory__factory";
export { FirstPriceAuction__factory } from "./FirstPriceAuction__factory";
