/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface AuctionFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activeAuctions"
      | "checkUpkeep"
      | "deployedAuctions"
      | "getActiveAuctionCount"
      | "getActiveAuctions"
      | "getAuctionsBySeller"
      | "getDeployedAuctions"
      | "getNFTRequestDetails"
      | "getPendingRequests"
      | "getRequest"
      | "getRequestCount"
      | "getRequestsBySeller"
      | "isActiveAuction"
      | "owner"
      | "performUpkeep"
      | "registerAuction"
      | "rejectRequest"
      | "requests"
      | "sellerAuctions"
      | "sellerRequests"
      | "submitAuctionRequest"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuctionApproved"
      | "AuctionRegistered"
      | "AuctionRejected"
      | "AuctionRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "activeAuctions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkUpkeep",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deployedAuctions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveAuctionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveAuctions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAuctionsBySeller",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDeployedAuctions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getNFTRequestDetails",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingRequests",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRequest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRequestCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRequestsBySeller",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isActiveAuction",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "performUpkeep",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAuction",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rejectRequest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sellerAuctions",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sellerRequests",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitAuctionRequest",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      AddressLike,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "activeAuctions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkUpkeep",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployedAuctions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveAuctionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveAuctions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAuctionsBySeller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDeployedAuctions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNFTRequestDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRequest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRequestCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRequestsBySeller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isActiveAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "performUpkeep",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rejectRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "requests", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sellerAuctions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sellerRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitAuctionRequest",
    data: BytesLike
  ): Result;
}

export namespace AuctionApprovedEvent {
  export type InputTuple = [requestId: BigNumberish, auction: AddressLike];
  export type OutputTuple = [requestId: bigint, auction: string];
  export interface OutputObject {
    requestId: bigint;
    auction: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuctionRegisteredEvent {
  export type InputTuple = [auction: AddressLike];
  export type OutputTuple = [auction: string];
  export interface OutputObject {
    auction: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuctionRejectedEvent {
  export type InputTuple = [requestId: BigNumberish];
  export type OutputTuple = [requestId: bigint];
  export interface OutputObject {
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuctionRequestedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    seller: AddressLike,
    title: string
  ];
  export type OutputTuple = [requestId: bigint, seller: string, title: string];
  export interface OutputObject {
    requestId: bigint;
    seller: string;
    title: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AuctionFactory extends BaseContract {
  connect(runner?: ContractRunner | null): AuctionFactory;
  waitForDeployment(): Promise<this>;

  interface: AuctionFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activeAuctions: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  checkUpkeep: TypedContractMethod<
    [arg0: BytesLike],
    [[boolean, string] & { upkeepNeeded: boolean; performData: string }],
    "view"
  >;

  deployedAuctions: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getActiveAuctionCount: TypedContractMethod<[], [bigint], "view">;

  getActiveAuctions: TypedContractMethod<[], [string[]], "view">;

  getAuctionsBySeller: TypedContractMethod<
    [seller: AddressLike],
    [string[]],
    "view"
  >;

  getDeployedAuctions: TypedContractMethod<[], [string[]], "view">;

  getNFTRequestDetails: TypedContractMethod<
    [requestId: BigNumberish],
    [[string, bigint] & { nftContract: string; nftTokenId: bigint }],
    "view"
  >;

  getPendingRequests: TypedContractMethod<[], [bigint[]], "view">;

  getRequest: TypedContractMethod<
    [requestId: BigNumberish],
    [
      [string, string, string, bigint, bigint, bigint, string, bigint] & {
        seller: string;
        title: string;
        description: string;
        durationMinutes: bigint;
        minimumBid: bigint;
        status: bigint;
        deployedAuction: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  getRequestCount: TypedContractMethod<[], [bigint], "view">;

  getRequestsBySeller: TypedContractMethod<
    [seller: AddressLike],
    [bigint[]],
    "view"
  >;

  isActiveAuction: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  performUpkeep: TypedContractMethod<
    [performData: BytesLike],
    [void],
    "nonpayable"
  >;

  registerAuction: TypedContractMethod<
    [requestId: BigNumberish, auctionAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  rejectRequest: TypedContractMethod<
    [requestId: BigNumberish],
    [void],
    "nonpayable"
  >;

  requests: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint
      ] & {
        seller: string;
        title: string;
        description: string;
        durationMinutes: bigint;
        minimumBid: bigint;
        nftContract: string;
        nftTokenId: bigint;
        status: bigint;
        deployedAuction: string;
        createdAt: bigint;
        processedAt: bigint;
      }
    ],
    "view"
  >;

  sellerAuctions: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  sellerRequests: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  submitAuctionRequest: TypedContractMethod<
    [
      _title: string,
      _description: string,
      _durationMinutes: BigNumberish,
      _minimumBid: BigNumberish,
      _nftContract: AddressLike,
      _nftTokenId: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activeAuctions"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "checkUpkeep"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [[boolean, string] & { upkeepNeeded: boolean; performData: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "deployedAuctions"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getActiveAuctionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getActiveAuctions"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getAuctionsBySeller"
  ): TypedContractMethod<[seller: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getDeployedAuctions"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getNFTRequestDetails"
  ): TypedContractMethod<
    [requestId: BigNumberish],
    [[string, bigint] & { nftContract: string; nftTokenId: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPendingRequests"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getRequest"
  ): TypedContractMethod<
    [requestId: BigNumberish],
    [
      [string, string, string, bigint, bigint, bigint, string, bigint] & {
        seller: string;
        title: string;
        description: string;
        durationMinutes: bigint;
        minimumBid: bigint;
        status: bigint;
        deployedAuction: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRequestCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRequestsBySeller"
  ): TypedContractMethod<[seller: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "isActiveAuction"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "performUpkeep"
  ): TypedContractMethod<[performData: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerAuction"
  ): TypedContractMethod<
    [requestId: BigNumberish, auctionAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rejectRequest"
  ): TypedContractMethod<[requestId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requests"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint
      ] & {
        seller: string;
        title: string;
        description: string;
        durationMinutes: bigint;
        minimumBid: bigint;
        nftContract: string;
        nftTokenId: bigint;
        status: bigint;
        deployedAuction: string;
        createdAt: bigint;
        processedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "sellerAuctions"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "sellerRequests"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitAuctionRequest"
  ): TypedContractMethod<
    [
      _title: string,
      _description: string,
      _durationMinutes: BigNumberish,
      _minimumBid: BigNumberish,
      _nftContract: AddressLike,
      _nftTokenId: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getEvent(
    key: "AuctionApproved"
  ): TypedContractEvent<
    AuctionApprovedEvent.InputTuple,
    AuctionApprovedEvent.OutputTuple,
    AuctionApprovedEvent.OutputObject
  >;
  getEvent(
    key: "AuctionRegistered"
  ): TypedContractEvent<
    AuctionRegisteredEvent.InputTuple,
    AuctionRegisteredEvent.OutputTuple,
    AuctionRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "AuctionRejected"
  ): TypedContractEvent<
    AuctionRejectedEvent.InputTuple,
    AuctionRejectedEvent.OutputTuple,
    AuctionRejectedEvent.OutputObject
  >;
  getEvent(
    key: "AuctionRequested"
  ): TypedContractEvent<
    AuctionRequestedEvent.InputTuple,
    AuctionRequestedEvent.OutputTuple,
    AuctionRequestedEvent.OutputObject
  >;

  filters: {
    "AuctionApproved(uint256,address)": TypedContractEvent<
      AuctionApprovedEvent.InputTuple,
      AuctionApprovedEvent.OutputTuple,
      AuctionApprovedEvent.OutputObject
    >;
    AuctionApproved: TypedContractEvent<
      AuctionApprovedEvent.InputTuple,
      AuctionApprovedEvent.OutputTuple,
      AuctionApprovedEvent.OutputObject
    >;

    "AuctionRegistered(address)": TypedContractEvent<
      AuctionRegisteredEvent.InputTuple,
      AuctionRegisteredEvent.OutputTuple,
      AuctionRegisteredEvent.OutputObject
    >;
    AuctionRegistered: TypedContractEvent<
      AuctionRegisteredEvent.InputTuple,
      AuctionRegisteredEvent.OutputTuple,
      AuctionRegisteredEvent.OutputObject
    >;

    "AuctionRejected(uint256)": TypedContractEvent<
      AuctionRejectedEvent.InputTuple,
      AuctionRejectedEvent.OutputTuple,
      AuctionRejectedEvent.OutputObject
    >;
    AuctionRejected: TypedContractEvent<
      AuctionRejectedEvent.InputTuple,
      AuctionRejectedEvent.OutputTuple,
      AuctionRejectedEvent.OutputObject
    >;

    "AuctionRequested(uint256,address,string)": TypedContractEvent<
      AuctionRequestedEvent.InputTuple,
      AuctionRequestedEvent.OutputTuple,
      AuctionRequestedEvent.OutputObject
    >;
    AuctionRequested: TypedContractEvent<
      AuctionRequestedEvent.InputTuple,
      AuctionRequestedEvent.OutputTuple,
      AuctionRequestedEvent.OutputObject
    >;
  };
}
