/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as baseAuctionSol from "./BaseAuction.sol";
export type { baseAuctionSol };
export type { AuctionFactory } from "./AuctionFactory";
export type { FirstPriceAuction } from "./FirstPriceAuction";
